### PR TITLE
Remote hosts file

### PR DESCRIPTION
**Pull request by cornelius**
This pull requests implements dynamic inclusion of the remote configuration, so that the shared remote `hosts.yaml` file doesn't have to be manually updated locally anymore, when it changes on the server.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged a1d43ad7914a6e3cf3865bc5643a5658cd06110a into 265b8c49f01dcf2b38eaae406188f438da284448 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d2185f64e6fd541a7c831c7cc75e5bcccd1ea9a9 into 265b8c49f01dcf2b38eaae406188f438da284448 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged d2185f64e6fd541a7c831c7cc75e5bcccd1ea9a9 into b66a4f9123ae912459fc00a98719b51eea20f657 )

**Comment by aduffeck** [comment]
lgtm

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 9802bad16affe0798779f90c32e5f4627e96a71d into b66a4f9123ae912459fc00a98719b51eea20f657 )

**Pull request merged**
