### PR TITLE
Lock info

### PR DESCRIPTION
**Pull request by cornelius**
Show info about who acquired a lock

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged a5280e2fd870e688459888f5678748f4acaf3d4c into 217a422ce3e3c3ae54cf4cd15ecff0ab8e7ec652 )

**Comment by tgoettlicher** [comment]
Besides hound's comment and the years in the license headers it looks good to me.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 2a409931cdd30a94b233e665e355c947acd626fa into 217a422ce3e3c3ae54cf4cd15ecff0ab8e7ec652 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged e5e5e5d9d95637ceee70cabc4a1b6ff095a6993a into 217a422ce3e3c3ae54cf4cd15ecff0ab8e7ec652 )

**Pull request merged**
